version: '3'
services:
  frontend:
    build:
      context: ./
    environment:
      - PORT=9045
      - NODE_ENV=development
    ports:
      - '9045:9045'
    volumes:
      - ./:/usr/src/app
    command: yarn dev
