version: '3'
services:
  frontend:
    build:
      context: ./
    environment:
      - PORT=3000
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
    command: yarn dev
